name: shell脚本

on:
  # push:
  schedule:
  # 每天6点10分（utc+8为北京时间）
    - cron: 10 22 * * *
  watch:
    types: started
  workflow_dispatch:
        
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检查分支
        uses: actions/checkout@v3
        
      - name: 执行shell脚本
        run: |
         #科学签到
         bash ./scripts/dotunnel_science_chekin.sh
         # secrets读取
         title='${{secrets.wechat_notification_title}}'
         token='${{secrets.wechat_notification_pushtoken}}'
         group='${{secrets.wechat_notification_group}}'
         cityname='${{secrets.wechat_notification_cityname}}'
         citycode='${{secrets.wechat_notification_citycode}}'
         weatherkey='${{secrets.wechat_notification_weatherkey}}'
         name1='${{secrets.wechat_notification_name1}}'
         name1birth='${{secrets.wechat_notification_name1birth}}'
         name2='${{secrets.wechat_notification_name2}}'
         name2birth='${{secrets.wechat_notification_name2birth}}'
         lovedate='${{secrets.wechat_notification_lovedate}}'
         name1date='${{secrets.wechat_notification_name1date}}'
         #通知脚本
         bash ./scripts/notification/wechat_notification.sh title token group cityname citycode weatherkey name1 name1birth name2 name2birth lovedate name1date
